### ISSUE TITLE
[Task]: Email Draft Responses

### ISSUE THREAD

**Issue by EOKENAVA** [HHS/simpler-grants-gov#1074]
### Summary

To be filled out by @CarleyKimball

**Comment by CarleyKimball** [comment]
**Emails recieved Dec. 19:**

From: Siporah.Jackson@treasury.gov
Sent: Tue Dec 19 17:12:22 2023
To: Simpler Grants
Cc:
Subject: Data Standards

Hi,

I would love to provide feedback as to how to make simpler.grants a great experience for stakeholders. Let me know if/when there is a good time to collaborate.

Thank you,

Siporah Jackson
Director, Financial Systems Integration and Oversight
Office of the Deputy CFO
U.S. Department of the Treasury


From: Wood, Roger
Sent: Tue Dec 19 19:28:50 2023
To: Simpler Grants
Cc:
Subject: API Design and Data Standards

Hi,

InfoEd Global is an eRA system vendor; our system is used by dozens of applicant institutions across the country for S2S submission to Grants.gov. We have supported S2S submission since the very beginning of S2S. Our goal is to leverage data available from Grants.gov and the agencies it supports in one user-friendly and consistent interface. Our client base includes institutions new to system-to-system submission as well as old hands that have been at it since the beginning. They vary in how they manage applications: some expect investigators with little administrative help to build applications while in other cases more sophisticated staff do most of the application development and submission for investigators.

We’d like very much to be involved in discussions and planning around data standards and access to data.

Thanks,
Roger

**Comment by CarleyKimball** [comment]
Please review the following documents containing responses to the above email inquiries:

[Jackson, Siporah](https://bpsconsulting.sharepoint.com/:w:/r/projects/hhs-grantsgov/ITS%20Documents/T8%20Communications%20and%20Outreach%20Support/Simpler.Grants.gov/Emails/Contact-us%20Email%20Drafts/Jackson,%20Siporah.docx?d=w8321ba3a3f234b01a5dfbe9f68a643ea&csf=1&web=1&e=FfU5gm)
[Wood, Roger](https://bpsconsulting.sharepoint.com/:w:/r/projects/hhs-grantsgov/ITS%20Documents/T8%20Communications%20and%20Outreach%20Support/Simpler.Grants.gov/Emails/Contact-us%20Email%20Drafts/Wood,%20Roger.docx?d=w576c7609a331498ca58b95fec65bfb15&csf=1&web=1&e=wIN2Iy)

**Comment by zoeb-nava** [comment]
Added my comments, thank you @CarleyKimball @alexis-bunc!

@rishalee how are you thinking about PAC recruitment? How would you like to track inbounds like these and how might we capture more information from them while we have their attention?

**Comment by CarleyKimball** [comment]
Shouldn't we keep this ticket open? Adriana has not reviewed. @zoeb-nava @sumiat

**Comment by acouch** [comment]
@CarleyKimball I removed the email above as we can't share [Personally Identifiable Information](https://csrc.nist.gov/glossary/term/PII) in this public channel.

**Comment by CarleyKimball** [comment]
@acouch We need to keep some PII available for the internal review process. Is it acceptable to just add links to the drafts we have in a restricted SharePoint? Otherwise, I am not sure how to handle certain comms in GitHub... CC: @sumiat
