### ISSUE TITLE
[Task]: Frontend tests for server components (search page, page not found)

### ISSUE THREAD

**Issue by rylew1** [HHS/simpler-grants-gov#1393]
### Summary

- Create new pattern for server component page tests 
- Fix existing tests that are failing/commented out - IE: `search.test.tsx`

### Acceptance criteria

- `search.test.tsx` successfully tests against a server component
- `not-found.test.tsx` tests against server component

### Notes
- Testing: server component search page gets initial results and passes to client component
- For the not found page: checking strings

**Comment by acouch** [comment]
@rylew1  can we move this to: https://github.com/HHS/simpler-grants-gov/milestone/155 since it is something we want to do before closing this line of work but is not blocking users from testing the search page?

**Comment by rylew1** [comment]
@sumiat I think we should put this one on hold in favor of working on the e2e ticket #1757  - the e2e tests will basically cover the server components.

**Comment by acouch** [comment]
We used to have these: https://github.com/HHS/simpler-grants-gov/blob/2024.5.13-1/frontend/tests/pages/404.test.tsx

We removed the page tests for e2e because of an error with `next-intl`:

![Image](https://github.com/user-attachments/assets/7b884878-0e26-4e81-8df9-5000235e7a6f)

The weird thing is is that the pages don't appear to be client components and can't figure out why the test suite thinks they are. I created an example in this branch https://github.com/HHS/simpler-grants-gov/commits/acouch/issue-1393-page-jest-tests/ 

`npm run test tests/pages/404.test.tsx` will generate that error.
