### ISSUE TITLE
[10k]: Search UI - Design and usability testing

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#1478]
### Definition

Create a design and incorporate existing testing for the initial #89 

### Business Goals

See: [Search UI public deliverable](https://app.gitbook.com/o/cFcvhi6d0nlLyH2VzVgn/s/Pm7UEzeiS1tbLCV1SFRu/product/deliverables/specifications/search-user-interface#business-value).

### In scope

See: [Search UI public deliverable](https://app.gitbook.com/o/cFcvhi6d0nlLyH2VzVgn/s/Pm7UEzeiS1tbLCV1SFRu/product/deliverables/specifications/search-user-interface#business-value).

### Out of scope

See: [Search UI public deliverable](https://app.gitbook.com/o/cFcvhi6d0nlLyH2VzVgn/s/Pm7UEzeiS1tbLCV1SFRu/product/deliverables/specifications/search-user-interface#business-value).

### Definition of Done

- [x] Search UI design approved 
- [x] Search UI designed so that users can search for opportunities by key word
- [x] Search UI designed so that  users can filter search results by at least one structured field (e.g. award date, opportunity type, etc.)
- [x] Search UI designed so that users can sort search results by at least one structured field (e.g. award date, title, etc.)
~At least 1 user research participant has been compensated for their time~
- [x] Documented findings for current search in grants.gov live ~and strategy for future search relevance~

**Comment by andycochran** [comment]
@sumiat , can you clarify the last DoD? 
> Documented findings for current search in grants.gov live and strategy for future search relevance

I'm not certain what this means, and it seems to be conflating a couple topics

**Comment by sumiat** [comment]
Yeah, agreed there's some conflation. The original intention if I remember correctly was do some research into the search in grants.gov live. We did this: https://github.com/HHS/simpler-grants-gov/issues/625 and this https://github.com/HHS/simpler-grants-gov/issues/629 and created the proposal to collect more analytics: https://docs.google.com/document/d/1W1dQcW-pG6BxiaKQifcJG3TyVTbFUIHQlK3GDxAtJXY/edit so I believe that part is done.

The strategy for relevance probably should have been updated because we moved that as a nice-to-have but we do have this ticket: https://github.com/orgs/HHS/projects/13/views/1?filterQuery=sprint+22&sliceBy%5BcolumnId%5D=66789336&sliceBy%5Bvalue%5D=Search+API&pane=issue&itemId=57740144 where we'll have a plan on how to handle relevancy. 

@widal001 - I want to check with you too! Do you remember if there was anything else with this DoD? or if we can update this DoD?

**Comment by widal001** [comment]
Thanks for tagging me on this in Slack @sumiat. This statement seems right to me:

> The original intention if I remember correctly was do some research into the search in grants.gov live.

I don't personally remember drafting the remaining AC and it doesn't seem to be in the DoD for Search UI so I think it's okay to amend/remove it and get this closed out!

**Comment by sumiat** [comment]
Thanks @widal001 I'll close this 10k.
