### ISSUE TITLE
[Task]: SIA for Ethnio

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#1508]
### Summary

SIA for Ethnio and maybe Zoom

### Acceptance criteria

- [ ] SIA document drafted for Ethnio (and Zoom, if needed)

**Comment by margaretspring** [comment]
@acouch Tried getting started on this, since I don't have access HHS Sharepoint I'm not sure when template to use,. You provided the Slack SIA as model... should I "Save As" that one or was there another empty template you'd shred. I'm not able to locate it now. 

Is this blocked until I have the HHS access or is there a template I can edit?

**Comment by margaretspring** [comment]
Got confirmation from Curtis Mayer at MH (tried to tag, but don't find his handle) that we don't need to submit since outside HHS systems.

**Comment by widal001** [comment]
Closing because issue was marked as 'Done' in https://github.com/orgs/HHS/projects/13
