### ISSUE TITLE
[Task]: Identify LOE for Supporting AWS QuickSight vs Hosted BI Tool

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#1509]
### Summary

We want to identify the level of effort for supporting AWS QuickSight vs a self-hosted tool like Metabase or Apache Superset. Both of those tools use Postgres for user / data storage and have supported docker containers. We would use the same ECR/S strategy we use for the frontend and backend. We will not need dev/stage versions. 

For QuickSight, LOE (in points) should include:

* User permissions that will need to be added and configured
  * Some will be needed to share dashboards publicly, some for adding non-dev users 
* Terraform implementation
* Logging / monitoring if needed
* Other security issues

For self-hosted tool:

* Setup of terraform to support ECR and ECS hosting
* Setting up Postgres database in AWS
* Logging / monitoring

### Acceptance criteria

- [ ] Steps for supporting each of the two options are detailed enough to be actionable and comprehensive
- [ ] Level of effort in estimated points is applied to each step and overall
- [ ] Major questions are surfaced 

###  Notes
- What is the LOE and other trade-offs to consider to set a self-hosted tool vs. something out of the box from AWS?

**Comment by coilysiren** [comment]
LEO Quicksight: 2 ~ 3 points. It's already setup with user management, you essentially just "turn it on" in the UI and then everything else is simple configuration.

LEO Self Hosted: 16 ~ 24 points, eg. 2 ~ 3 sprints. This includes the time to get the compute running (ECR / ECS / EC2 / whatever it is), the data store that it will need (RDS or otherwise), and figuring out the access control (ie. user accounts, and more importantly the VPN)

**Comment by widal001** [comment]
Closing because issue was marked as 'Done' in https://github.com/orgs/HHS/projects/13

**Comment by coilysiren** [comment]
Here is the result of my scoping,

<img width="778" alt="image" src="https://github.com/HHS/simpler-grants-gov/assets/5768468/ff16e6a4-49f6-4c4a-8b58-6a14bbc82809">

QuickSight: 10 points
Metabase (or _**anything**_ self hosted): 24 points
