### ISSUE TITLE
[Task]: Delivery Dashboard - Deploy application with CI/CD

### ISSUE THREAD

**Issue by coilysiren** [HHS/simpler-grants-gov#1549]
### Summary

Deploy the analytics application with CI/CD, via a `cd-analytics` file

### Acceptance criteria

- [ ] `cd-analytics` file works in all environments

**Comment by coilysiren** [comment]
This might already be done. I just need to wait to test it

**Comment by coilysiren** [comment]
https://github.com/HHS/simpler-grants-gov/blob/main/.github/workflows/cd-analytics.yml

via https://github.com/HHS/simpler-grants-gov/pull/1566

**Comment by aplybeah** [comment]
Update: Will be testing as a part of #1291. Will close when that one is merged

**Comment by aplybeah** [comment]
As stated yesterday, this will be tested as a part of #1291 because the DOD requires the cd-files for analytics, frontend and api to be deployed to staging. 

[Run: FE](https://github.com/HHS/simpler-grants-gov/actions/runs/8897803366/job/24433820616)
```
│ Error: putting WAFv2 WebACL Logging Configuration (arn:aws:wafv2:us-east-1:315341936575:regional/webacl/frontend-staging-wafv2-web-acl/38a04ec9-6646-45e9-818c-8f29fa88ce0f): WAFLogDestinationPermissionIssueException: Unable to deliver logs to the configured destination. You might need to grant log delivery permissions for the destination. If you're using S3 as your log destination, you might have exceeded your bucket limit.
│ 
│   with module.service.aws_wafv2_web_acl_logging_configuration.WafWebAclLogging,
│   on ../../modules/service/waf.tf line 195, in resource "aws_wafv2_web_acl_logging_configuration" "WafWebAclLogging":
│  195: resource "aws_wafv2_web_acl_logging_configuration" "WafWebAclLogging" {
```

Everything else seemed to work alright

[Run: anaIytics](https://github.com/HHS/simpler-grants-gov/actions/runs/8897665183)

```
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
1
make: *** [Makefile:170: sprint-burndown] Error 1
```

[Run: API](https://github.com/HHS/simpler-grants-gov/actions/runs/8897977574) Success
