### ISSUE TITLE
[Task]: Change "Newsletter" to "Subscribe"

### ISSUE THREAD

**Issue by andycochran** [HHS/simpler-grants-gov#1560]
### Summary

The page at https://simpler.grants.gov/newsletter should be updated to use the term "subscribe" instead of "newsletter" (as the later implies regular cadence). 

- Change the page route to `https://simpler.grants.gov/subscribe`
- Redirect `/newsletter` to `/subscribe` to preserve old links floating around (Note: Maybe this shouldn't be a 301/308 permanent redirect, but just handled in the app, as it's possible we'll want the `/newsletter` some time in the future — eng to sort out best option)
- Change the site navigation item to "Subscribe" 
- Change the breadcrumb to "Subscribe" 
- Change the page title (`h1`) to "Subscribe to project updates" 
- Change the intro paragraph to "If you sign up for the Simpler.Grants.gov product updates, we’ll keep you informed…"
- Change the disclaimer to "The Simpler.Grants.gov email subscriptions are powered by the Sendy…"

### Open questions: 
- Is "Updates" or "Subscribe" or "Signup" a better CTA for the URL / menu? The `/process` and `/research` pages have a "Sign up for project updates" CTA.

### Acceptance criteria

- [ ] The term "newsletter" is no longer used in production 
- [ ] Be sure to check that all the content is updated ("find all" in code for `newsletter`) 
- [ ] match the mockup [from comment below](https://github.com/HHS/simpler-grants-gov/issues/1560#issuecomment-2023851171)

**Comment by andycochran** [comment]
@meghscase / @sumiat, Do y'all have any insight on the open Q about the terms we're using for the mailing list?

**Comment by sumiat** [comment]
I don't @andycochran. Did this feedback to change from "newsletter" to "mailing list" come from somewhere?  I could see that people may understand that the newsletter is sent on a certain frequency but didn't necessarily associate it that way myself. I like "subscribe" because it seems generic but that's just based on an emotional/what i've seen response, not based on data or input. I wonder if it's worth updating the content in the site to note that we're only sending out updates when we have them, nothing on a regular frequency right now?

**Comment by andycochran** [comment]
> Did this … come from somewhere?

This came up in conversation with Adriana, @CarleyKimball, @lucasmbrown-usds, and @itsemilyianacone.

**Comment by CarleyKimball** [comment]
Hi team, copying over some email back and forth on this topic that came up through our email template approvals process:

From @lucasmbrown-usds 
"A couple small notes: 

1. Carley, I think you brought up replacing the “newsletter” term with “mailing list,” since as of right now, we don’t send newsletters at a regular interval and mailing list might be more appropriate to imply occasional updates rather than a schedule. But no problem if you want to keep references to newsletter."

My response:
"Hello Lucas,

I like your idea of pivoting away from “newsletter.” However, if we take that path, the website and link [https://simpler.grants.gov/newsletter] should be updated from “newsletter” to “mailing list” as well for consistency. 

Thoughts?"

Adriana:
"Hi Lucas & Carley – I was just thinking about Carley’s comment- Agree with her comment. I suggest we keep it as “newsletter” until is changed on the website if that is the approach that we want to take…. Maybe some discussion with Andy could be helpful."

Lucas:
"Agreed. +Andy/Emily: what do y’all think about changing website language from “newsletter” to “mailing list”? As of right now, we don’t send newsletters at a regular interval and mailing list might be more appropriate to imply occasional updates rather than updates on a regular schedule. 

What do you think?"

@sumiat @andycochran

**Comment by CarleyKimball** [comment]
We talked about it a bit more in our bi-weekly branding meeting. It seemed like most were on board with this change. 

We would need to know the timeline for this change, as we will need to make adjustments to our second batch of templates before we send those up through the approvals process.

**Comment by CarleyKimball** [comment]
For @sumiat's comment about "subscribe" I think that term can stay - we just were looking to change "newsletter" to "mailing list" to avoid the assumption of regular newsletters being sent out. "Mailing list" is more comprehensive and can cover all types of communications.

**Comment by andycochran** [comment]
> "Mailing list" is more comprehensive and can cover all types of communications.

The open question I put in the description is getting at how we might not need to refer to the list in a way that implies anything more specific than signing up for project updates. We might avoid using an explicit noun altogether here — e.g. change the URL to `/subscribe`, and here's a quick mockup: 

<img width="1552" alt="image" src="https://github.com/HHS/simpler-grants-gov/assets/409279/00c77807-73a9-46e6-bc38-c307862297e7">

**Comment by CarleyKimball** [comment]
Oh I like this option! Can you share in comms thread and tag Adriana? I don't think she's too involved on Github.

**Comment by acouch** [comment]
There was a PR here that partly implemented this: https://github.com/navapbc/simpler-grants-gov/pull/111/files
