### ISSUE TITLE
[Task]: Add environment variables file to analytics folder

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#1598]
### Summary

* add environment folder that can pass database connection credentials
* can use [local.env](https://github.com/HHS/simpler-grants-gov/blob/main/api/local.env), [.env.ENV](https://github.com/HHS/simpler-grants-gov/blob/main/frontend/.env.development), or other format
* sync w/ terraform envar strategy for the [analytics container](https://github.com/HHS/simpler-grants-gov/issues/1547)

### Acceptance criteria

- [ ] env var file with at vars to connect to a local database (actual connection doesn't need to be tested)

**Comment by widal001** [comment]
@acouch Just as an FYI the analytics package supports this with [dynaconf](https://www.dynaconf.com/configuration/#dotenv_path). Right now the default file type supported is `.toml` and environment variables. If we wanted to use a `.env` instead of `.toml` we should only have [to change this file](https://github.com/HHS/simpler-grants-gov/blob/main/analytics/config.py)

**Comment by sumiat** [comment]
@coilysiren completed this
