### ISSUE TITLE
[Task]: Remove "Select at least one status" from search ui

### ISSUE THREAD

**Issue by rylew1** [HHS/simpler-grants-gov#1958]
### Summary

![image](https://github.com/HHS/simpler-grants-gov/assets/93001277/4d6c15ed-5d05-4882-bdd9-b75a18fb5d41)

Sentence doesn't make much sense as is (see image)

### Acceptance criteria

- Removed `"Select at least one status.`" message

**Comment by rylew1** [comment]
@andycochran can you verify this one is what we want as well?

**Comment by andycochran** [comment]
Yup, LGTM. 

Context: This sentence was in the Figma because the original function of the status filters would show zero results if no statuses were checked. This was supposed to let the user know they have to check at least one. However, we pivoted so that the status filter now behaves as the other filters: if none are checked, results are shown for all statuses.
