### ISSUE TITLE
[Deliverable Spec]: Open source onboarding process

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#221]
### Description

Create the individual milestone document for the Open source onboarding process 30k #72 

### Definition of Done

- [x] deliverable spec created in the public wiki

**Comment by widal001** [comment]
@sumiat @EOKENAVA @sarahknoppA6 Since we're moving to a pattern where we're only creating full milestone docs for north star milestones, I wanted to repurpose this ticket for the Open Source Group Kickoff milestone doc (the north star milestone that recurring meetings rolls up into)

We can just use the [Setup recurring meetings ticket](https://github.com/HHS/grants-equity/issues/46) to reflect the meetings that need to be created.

**Comment by EOKENAVA** [comment]
That is perfectly fine. Thanks @widal001

**Comment by widal001** [comment]
Pausing work for the time being in favor of:

- #574 
- #581

**Comment by sumiat** [comment]
Added a draft of this deliverable specification. PR #980. @widal001 to review next.

**Comment by sumiat** [comment]
deliverable spec created in the public wiki and will be update to github when approved by Lucas
