### ISSUE TITLE
Ensure that the Opportunity Listing page is consistent about hiding vs rendering empty values

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#2321]
### Summary

Some of the opportunity page items are hidden if there is no data, and some are not. This should be cleaned up and be consistent.

### Acceptance criteria

- [ ] check with design / product about correct pattern (ie what should be shown vs not if there is no data)
- [ ] implement pattern
- [ ] ensure testing complies

**Comment by mxk0** [comment]
@andycochran to post Figma link.

**Comment by crystabelrangel** [comment]
https://www.figma.com/files/team/1329563746319512353/project/196525874/Simpler-Grants-Project?fuid=1329605892244385679

**Comment by doug-s-nava** [comment]
Field details for opportunities https://docs.google.com/spreadsheets/d/163cqQy9SdJIPFOBDwJV9fuqG0xougo0O_QMjl0PFod8/edit?gid=0#gid=0

**Comment by andycochran** [comment]
@doug-s-nava Let me know if you would like to sync with the design team and go through all the edge cases, or if we need to make individual design tasks to resolve

**Comment by doug-s-nava** [comment]
Changes to be made as part of this change after discussion with @chouinar and @crystabelrangel:

* add double dash for null values to all 4 grid boxes, prefixed by $ for money values
* replace double dash with em dash for null assistance listings (do not worry about handling cases for individual missing values within assistance listings)
* fix display of version, use -- if null (write test for date util)
* add a -- in status widget next to "Closing" when null and status is posted
* add double dash under eligible applicants when null
* for applicant_eligibility_description make sure to strip out any markup
* for agency name, ensure that we are using the top level rather than summary value
* add double dash under description when null
* for link to additional information, use link url for text if description is missing
* for contact create sections:
    * description
    *  email (email description, newline - email address linked to mailto)
    * phone
    * -- if any are absent (other than email description)


For later:

* what to do other than hiding the status box when there is no opportunity status
* we should put posted date and closing date description on a new line under the date, and hide / expand after X characters

**Comment by crystabelrangel** [comment]
Figma in devmod with comments: https://www.figma.com/design/FGxWtAgToKhehLJCiuy1zL/Simpler.Grants.gov-Project?node-id=1-10&m=dev

Four mockups for:
- Null values
- Null status
- Closed status
- Forecasted status
