### ISSUE TITLE
Going directly to search page de-selects default opportunity status filters

### ISSUE THREAD

**Issue by lucasmbrown-usds** [HHS/simpler-grants-gov#2510]
### Summary

We will probably often send people directly to `https://simpler.grants.gov/search`. When visiting that URL, however, it means that no opportunity statuses are selected for the filter. Is it a desired behavior for the default experience when landing on `https://simpler.grants.gov/search` to have it select "Posted" and "Forecasted" as default filters turned on?

### Reproducibility

I tried multiple times and saw the bug every time

### How to reproduce the bug

1. Visit https://simpler.grants.gov/search (not via the Nav)
2. Notice that no opportunity status filters are selected. 
3. Should "Forecasted" and "Posted" be selected by default?

Does this need selected=none?

### Browser

Chrome

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by mxk0** [comment]
For the record, discussion in Simpler Slack: https://betagrantsgov.slack.com/archives/C05TGEL3C6Q/p1730222998385329

**Comment by mxk0** [comment]
@acouch @andycochran mind documenting what we want to do here in a comment?

**Comment by acouch** [comment]
Change the logic to the following:

### 1. user visits `/search`

forecasted,posted selected:
![Image](https://github.com/user-attachments/assets/2b3cafee-f399-45d3-9bcd-a4df497fba73)

### 2. user deselects all statuses

statuses stay un-selected

`status=none` for no status selected in the URL

![Image](https://github.com/user-attachments/assets/3738990b-fb10-458d-bb87-4b1d0879b3a1)

### 3. user selects one status when none are selected

`status=none` is replaced by the selected status:

![Image](https://github.com/user-attachments/assets/71fe82d2-1e26-4ab8-a2c1-4893dbacecf1)

### 4. all other user selections and actions stay the same

**Comment by andycochran** [comment]
Proposed AC: 
- The default view of `/search` without query parameters should have "Forecasted" and "Posted" status filters selected
- If the user deselects all statuses, the query parameters should contain `status=none`, which should include opportunities of all statuses in the results since a status filter will not be applied
  - While it might be confusing that `none` returns _all_ statuses, the parameter indicates that no statuses are _selected_. 
  - From a results perspective, there's no difference in every status being selected or none being selected. But when all are selected, the UI is represented with the parameter `status=forecasted,posted,closed,archived`

**Comment by andycochran** [comment]
I think we just said the same thing 😆 but yours is better w/ visuals

**Comment by acouch** [comment]
Great 🧠 think alike :)
