### ISSUE TITLE
Design for document and NOFO edge cases

### ISSUE THREAD

**Issue by doug-s-nava** [HHS/simpler-grants-gov#2636]
### Summary

In order to build a full UI for documents we should make decisions and draw up designs and or UI requirements for:

* case where an opportunity has no associated documents
* case where an opportunity has no documents that would fall into either the "Related documents" or "Application forms" sections
* case where an opportunity has multiple "NOFO" documents and a user clicks the "Download Full Grant Details" button

### Acceptance criteria

designs and or UI requirements are created for the cases mentioned above

**Comment by crystabelrangel** [comment]
@doug-s-nava @emilycnava here is the [Figma in Dev Mode](https://www.figma.com/design/FGxWtAgToKhehLJCiuy1zL/Simpler.Grants.gov-Project?node-id=607-14094&m=dev)

For the edge case of multiple NOFO files, we discussed this with @chouinar and @emilycnava, since these seven NOFO opportunities will only have one NOFO file we will not have multiple files. We can look into only downloading the latest one or downloading a zip file down the line.
