### ISSUE TITLE
Search does not successfully partial match on opportunity number

### ISSUE THREAD

**Issue by lucasmbrown** [HHS/simpler-grants-gov#2775]
### Summary

My expectation was that if we search for a grant using *part* of the opportunity number, it would match on the result. This does not appear to be working. 

### Reproducibility

I tried multiple times and saw the bug every time

### How to reproduce the bug

1. Go to https://simpler.grants.gov/search 
2. Search for "FY25-BSB" (or a part of the opportunity number for any opportunity listing). 
3. Notice no results appear. 
4. Search for "FY25-BSB-410601" (or the full opportunity number for any opportunity listing). 
5. Notice that your result will appear. 

I would've expected the partial match to succeed. 

![Image](https://github.com/user-attachments/assets/6208dd3c-fe8f-4c67-8693-f5fb28fd48ef)

### Browser

Chrome

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by chouinar** [comment]
I think this mostly comes down to how we specify which fields to search against.

The opportunity number being a text field actually gets stored twice in the search index. A tokenized version, and a "keyword" version. How that would look would be:
* tokenized: `["FY25", "BSB", "410601"]`
* keyword: `FY25-BSB-410601`

The idea is for text fields whether you want to consider them as several separate "words" (for example, the title or description) or as a singular "thing" (for example, the opportunity status). This is a weird case where we sorta want both? If you query us with the full opportunity number, we want to match exactly. Additionally, if you want to query us with `FY25-BSB*` that also works right now.

When we query the search index, we can tell it to query against either of these. Right now we have it configured to query against the "keyword" value only.

To support `FY25-BSB` we'd need to query against both fields. That way when it tokenizes the query string, it matches `FY25` and `BSB` on both.

This is all technically simple, the only question (that doesn't need to be solved now) is how this affects scoring. Each field that a query matches against increases the score, if something technically matches both fields (eg. passing `FY25-BSB-410601`), that would effectively double-weight, but since that likely only causes a single result anyways, I'm not sure that really matters?

**Comment by lucasmbrown-usds** [comment]
> how this affects scoring

Yup, and if someone searches `FY25-BSB-410601` and that double-counts on their score, I do think they'll be happy to see the `FY25-BSB-410601` opportunity appear at the top of the list, If, for some reason, that matches on more than one opportunity.
