### ISSUE TITLE
Create database table `ExtractMetadata` to store extract files

### ISSUE THREAD

**Issue by mikehgrantsgov** [HHS/simpler-grants-gov#2791]
Related to [2454](https://github.com/HHS/simpler-grants-gov/issues/2454)

### Summary

The legacy website provides the ability to download XML extracts of opportunity data: https://www.grants.gov/xml-extract - this is something we should also support. Having extracts (especially if they're just the same data as our search endpoints) reduces the traffic our search endpoint will need to handle as we can point anyone that would want to scrape our data to an extract file.

Create a table to track extract metadata. 

Something like:
```

# Create LkExtractType as a lookup value with opportunities_xml and opportunities_csv as initial values

class ExtractMetadata(Base):
    __tablename__ = 'extract_metadata'

    extract_metadata_id = Column(BigInteger, primary_key=True, autoincrement=True)
    extract_type = Column(LkExtractType, nullable=False)
    file_name = Column(String, nullable=False)
    file_path = Column(String, nullable=False)
    file_size_bytes = Column(BigInteger, nullable=False)
    created_on = Column(DateTime, server_default=func.now(), nullable=False)
    updated_on = Column(DateTime, server_default=func.now(), onupdate=func.now(), nullable=False)

```

### Acceptance criteria

- [ ] Model created
- [ ] Database migration generated

**Comment by chouinar** [comment]
A few small suggestions:
* `extract_metadata_id` instead of `id` for the primary key - also make it a BigInteger to follow the pattern of other tables (doubt we hit the ~4 billion limit of a regular int, but just in case)
* To match the other attachment table we have, might just adjust names and such like it (eg. `file_size_bytes` as BigInteger).
* Extract type could be a lookup value maybe? Not sure what you were thinking in terms of organization (something like `opportunities_xml` and `opportunities_csv` as values?)

**Comment by mikehgrantsgov** [comment]
Thanks, adapted this!
