### ISSUE TITLE
[Task]: Configure Alerts for Static Site Launch

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#484]
### Summary
In #414, we determined what alerts need to be set up for the static site launch. In this work, we want to configure those alerts.

### Notes / Resources
- https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/US_SetupSNS.html
- Documentation available from MH, check with @acouch. Available in the grants.gov security folder. 

Use infra capabilities to set up alerts to email or incident response service: https://github.com/navapbc/template-infra/blob/main/docs/infra/set-up-monitoring-alerts.md

- We have not determined an incident management service. For now, we will use email. 

### Acceptance criteria

- [x] Add any additional alerts that are necessary for the static site launch
- [ ] Route alerts to appropriate parties through email (short term solution).

**Comment by acouch** [comment]
Noting from the linked ticket, each of the 3 alarms for each service should send notifications to the internal slack channel and email addresses which are documented in the Internal Incident Response Plan.

**Comment by daphnegold** [comment]
> Add any additional alerts that are necessary for the static site launch

Conversations offline indicated the current alerts are sufficient for now.

**Comment by daphnegold** [comment]
Discussion in sprint planning indicated that we are using email as a notification method for now, integrating with Slack alone or with an incident management service. I suggest rather than go through the lift of direct CloudWatch => Slack integration, we choose an incident management service that integrates with Slack and avoid extra work that can be done for us. An example would be PagerDuty.

**Comment by daphnegold** [comment]
Discussion in sprint planning indicated that we are using email as a notification method for now, not integrating with Slack alone or with an incident management service. 

I suggest rather than go through the not insignificant lift of direct CloudWatch => Slack integration, we choose an incident management service that has Slack capabilities and avoid extra work that can be done for us. An example would be PagerDuty.

**Comment by acouch** [comment]
@daphnegold agreed, thanks. We can create another ticket for slack integration in the future.
