### ISSUE TITLE
[ADR]: Logging and monitoring platform for front-end and back-end

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#630]
### Description

ADR to select a tool to send logging metrics such as New Relic. Consider what would be required for the first release of the Developer Preview and what tool would be set up for the long term strategy. 

### Approvers

Lucas and/or Billy 

### Options

- New Relic
- Splunk
- Cloudwatch
- Sentry
- Datadog
- Grafana

### Users
* Application developer
* HHS 
* Non-developers on high level performance

### Decision Criteria

* Interoperability: be able to connect to a visualization tool so that it can be connected with the public measurement dashboard
* API metrics: how many people are hitting the API
* Debugging capabilities
* Log searching and insights: find the issues such as slow queries that are causing issues 

### Definition of Done

- [ ] The approvers for this decision have been identified (ideally before work on the ADR starts)
- [ ] The ADR is created and stored in `documentation/decisions/adr` with status "Accepted"
- [ ] The ADR has been reviewed and approved by the approvers: Lucas and/or Billy
- [ ] The ADR satisfies requirements that are outlined in the ADR template
- [ ] Any follow-up tickets have been created to implement the logging and monitoring tool

**Comment by coilysiren** [comment]
Here's a good blog post that compares Datadog with New Relic: https://betterstack.com/community/comparisons/datadog-vs-newrelic/

**Comment by coilysiren** [comment]
I don't see any need to focus on interoperability here. The platforms aren't generating our tracking metrics, those metrics are being generated by our application. So there no need to, for example, hook up new relic into airflow. We could hook our application into airflow directly, and skip the middle man.

**Comment by coilysiren** [comment]
From my research, Splunk / New Relic / Datadog all have a similar feature set. It's difficult to find decision criteria for which all 3 aren't a "yes"

Sentry and Cloudwatch stand out here, in that

Sentry isn't (yet) built as a fully featured logging and monitoring platform. Instead, sentry is focused pretty narrowly on handling exceptions, and primarily frontend exceptions at that.

Cloudwatch comes for free with AWS. As a free product that comes bolted onto a platform like AWS, it hasn't gotten anywhere near the care and attention of the other platforms on this list. To be frank, the UX of cloudwatch is terrible, and this becomes clear very quickly when comparing it to any other platform.

**Comment by coilysiren** [comment]
What I do see missing here is a fully open source option like Prometheus + Grafana. I'm not sure I want to open that can of worms, though.

**Comment by coilysiren** [comment]
I think there's some historical context that might help make a decision here. I'm doing these from memory so it might be slightly inaccurate.

Solunk, to my knowledge, started as a data observability platform

New Relic started as an APM-ish platform 

Datadog started as a metrics platform

As such, they all have capabilities that they are best at. Splunk is better when you are using a data heavy platform (we aren't!). Datadog is better when you have a lot of metrics that you care about (IMO we don't! Not beyond the standard ones). Datadog is consistently mentioned as having the best dashboards, due to it's metrics background.

**Comment by coilysiren** [comment]
I've talk myself into a place where we can make a decision!!!

New Relic is the better choice if we care the most about optimizing around the UX of users are they move through the platform. New Relic's APM tooling will be our most valuable asset here.

Datadog is a better choice is we care the most about the aggregate out comes and statistics of our users at large. That's because Datadog is better at creating dashboards from arbitrary metrics.

I'll try to capture this all in long form ADR format... 🤔

**Comment by coilysiren** [comment]
New Relic and Datadog do compare on pricing, I should mention that.

Additionally, I should run a familiarity survey with the team. I think a lot of the team has existing New Relic experience that we can leverage, more-so than Datadog.

**Comment by neel-middleware** [comment]
Hey @coilysiren your point on New Relic and Datadog pricing is on point.

I would also like to add Middleware.io  here which also fulfills all the above-mentioned criteria, do let me know if any details are required.
