### ISSUE TITLE
[Task]: Load testing

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#696]
### Summary

- Load test to handle at least 1000 concurrent users at one time.
- Use Apache Workbench

### Acceptance criteria

- [ ] Run a load test to handle 1000 concurrent users to understand load times

### Notes
- This work is one factor in #555

**Comment by SammySteiner** [comment]
I first want to determine realistic load based on the current grants.gov that we need to build against.
Looking at the google analytics data, I'm going to pull out a few numbers:
1.  Avg. Session Duration is 6 minutes 40 seconds
2. 11.33 events per session 

That comes to ~.028 events per second per user. Assuming 1k users, that's testing for a load of 28 requests per seconds for 1000 concurrent users.

A quick test of 1000 requests at 30 requests per second against beta.grants.gov showed the following results:

![Image](https://github.com/HHS/simpler-grants-gov/assets/25465464/68d245f3-6105-42ea-96b8-334710a680a7)

However, in order to build testing into our ci-cd pipeline and to facilitate quick load testing in the future, I'll add an artillery.io script for the future.

**Comment by SammySteiner** [comment]
Artillery script results:


![Image](https://github.com/HHS/simpler-grants-gov/assets/25465464/7e7ba862-9f10-41c7-81ca-1ec08a1a16e5)
