### ISSUE TITLE
[Task] Update layout of the roadmap on the process page

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#873]
- Add border below high-level roadmap
- Add chevron icons between each column
- Add new small heading above each milestone, indicating the associated high-level item
- Update the milestone titles 

![Image](https://github.com/HHS/simpler-grants-gov/assets/409279/229d6487-5ef9-4690-90e9-1892baab8f42)

**Comment by andycochran** [comment]
Thinking about how the chevrons might be added. 

**Idea 1:** 
- Add 2 columns containing just a chevron icon
- Put the `.display-none` and `.table-lg:display-block` classes on those columns so they don't show when the grid is stacked
Caveat: This might be difficult to get the column sizes right. The chevron columns would need to shrink while the others fill the available width. 

**Idea 2:** 
- Add a chevron icon at the end of the first two columns 
- Put the `.display-none` and `.table-lg:display-block` classes on the icons 
- Put `.position-relative` on the columns
- Use `.position-absolute` to position the icon relative to the column 
- Use `.right-full`, `.margin-right-[n]`, and `.top-[n]` to position the icon into the gutter
- We might need to explicitly set `.grid-gap-lg` so that there's enough room for the chevrons. 
Caveat: This is more complex. But I like it 'cause it doesn't mess with the existing columns. 

@SammySteiner @acouch Thoughts?
